<Page>:
    size: self.size
    pos: self.pos
    orientation: "vertical"
    canvas:
        Color:
            rgba: 0,1,1,1
        Rectangle:
            size: self.size
            pos:self.pos
    AcceptButton:
        id: accept_button
        text: "Accept Mission"

    # AcceptButton2:
    #     id: accept_button2
    #     text: "Accept Mission"
    #     on_touch_up: root.accept_mission()
    #     #on_disabled: self._update_color()

